sonar.projectKey=frontend-vite
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/index.ts,**/types.ts,src/test/**,generate/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/index.ts,**/types.ts,src/test/**,generate/**,src/vite-env.d.ts
sonar.qualitygate.wait=true
sonar.login=squ_20f4835a20b16839fe7a52b4d43ff97224e640d1

# Ignore CSS unknown at-rule for Tailwind V4
sonar.issue.ignore.multicriteria=css1,a11y1,a11y2,ts1,ts2,ts3,ts4,ts5,ts6
sonar.issue.ignore.multicriteria.css1.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.css1.resourceKey=**/*

# Ignore specific Radix UI / Combobox accessibility warnings in DynamicSelect
sonar.issue.ignore.multicriteria.a11y1.ruleKey=javascript:S6848
sonar.issue.ignore.multicriteria.a11y1.resourceKey=**/*
sonar.issue.ignore.multicriteria.a11y2.ruleKey=javascript:S6852
sonar.issue.ignore.multicriteria.a11y2.resourceKey=**/*

# Ignored TS rules
sonar.issue.ignore.multicriteria.ts1.ruleKey=typescript:S6759
sonar.issue.ignore.multicriteria.ts1.resourceKey=**/*
sonar.issue.ignore.multicriteria.ts2.ruleKey=typescript:S4325
sonar.issue.ignore.multicriteria.ts2.resourceKey=**/*
sonar.issue.ignore.multicriteria.ts3.ruleKey=typescript:S1874
sonar.issue.ignore.multicriteria.ts3.resourceKey=**/*
sonar.issue.ignore.multicriteria.ts4.ruleKey=typescript:S6671
sonar.issue.ignore.multicriteria.ts4.resourceKey=**/*
sonar.issue.ignore.multicriteria.ts5.ruleKey=typescript:S6582
sonar.issue.ignore.multicriteria.ts5.resourceKey=**/*
sonar.issue.ignore.multicriteria.ts6.ruleKey=typescript:S6819
sonar.issue.ignore.multicriteria.ts6.resourceKey=**/*
